# Remediate Auto-Healing Agent Configuration

    version: 1

# =============================================================================
# API KEYS
# =============================================================================
# Required for AI-powered diagnosis. Set via environment or directly here.
api_keys:
  gemini: AIzaSyCZlpaK6qAR2BOX3sh6pUHRRc4ce5TyiB8      # Required: Google Gemini API key
  bear1: ${BEAR1_API_KEY}        # Optional: Token compression (reduces costs)
  github_token: ${GITHUB_TOKEN}  # Required for GitHub Actions collector
  render: rnd_qQc1dLYHOg2R8LlAUFefV7lkIr0M # Required for Render platform integration
  vercel: ${VERCEL_TOKEN}        # Required for Vercel platform integration

# =============================================================================
# COLLECTORS - What to Monitor
# =============================================================================
# Enable the collectors relevant to your setup.
collectors:

  # ---------------------------------------------------------------------------
  # FILE COLLECTOR - Monitor local log files
  # ---------------------------------------------------------------------------
  - type: file
    enabled: true
    paths:
      - ./logs/*.log
      - ./logs/**/*.log
      # Add your application log paths:
      # - /var/log/myapp/*.log
      # - /var/log/nginx/error.log
    error_patterns:
      - ERROR
      - FATAL
      - Exception
      - Traceback
      - failed
    exclude_patterns:
      - DEBUG
      - healthcheck
      - metrics
    tail_lines: 500

  # ---------------------------------------------------------------------------
  # DOCKER COLLECTOR - Monitor Docker container logs
  # ---------------------------------------------------------------------------
  - type: docker
    enabled: false
    # Option 1: Specific container names
    containers:
      - myapp
      - mydb
      - redis
    # Option 2: Pattern matching (uncomment to use)
    # container_patterns:
    #   - "myapp-.*"
    #   - ".*-worker"

  # ---------------------------------------------------------------------------
  # KUBERNETES COLLECTOR - Monitor K8s pod logs
  # ---------------------------------------------------------------------------
  - type: kubernetes
    enabled: false
    namespace: default
    # Filter by labels (recommended for production)
    # label_selector: "app=myapp,env=production"
    # Or specific pod names
    # pod_names:
    #   - myapp-deployment-abc123

  # ---------------------------------------------------------------------------
  # GITHUB ACTIONS COLLECTOR - Monitor CI/CD workflow logs
  # ---------------------------------------------------------------------------
  - type: github_actions
    enabled: false
    owner: your-org        # GitHub organization or username
    repo: your-repo        # Repository name
    # Optional filters:
    # workflow_name: CI    # Only monitor specific workflow
    # branch: main         # Only monitor specific branch

  # ---------------------------------------------------------------------------
  # RENDER COLLECTOR - Monitor Render platform services
  # ---------------------------------------------------------------------------
  - type: render
    enabled: true
    # Optional: filter to specific services (monitors all if not specified)
    # service_names:
    #   - my-web-service
    #   - my-api-service
    #   - my-worker

# =============================================================================
# EXECUTORS - How to Fix Issues
# =============================================================================
# Configure what remediation actions are available.
executors:

  # ---------------------------------------------------------------------------
  # FILE EXECUTOR - Edit code, fix configs, create files
  # ---------------------------------------------------------------------------
  # IMPORTANT: This enables AI to fix code errors via search/replace
  - type: file
    enabled: true
    # SECURITY: Only allow file edits within these directories
    base_paths:
      - .                              # Current project directory
      # Add your project paths:
      # - /home/user/myproject
      # - /var/www/myapp/src
    # SECURITY: Never allow edits to these paths (even if inside base_paths)
    blocked_paths:
      - /etc
      - /usr
      - /bin
      - /sbin
      - ~/.ssh
      - ~/.aws
      - node_modules                   # Don't edit dependencies
      - venv
      - .git

  # ---------------------------------------------------------------------------
  # GIT EXECUTOR - Revert commits, apply patches
  # ---------------------------------------------------------------------------
  - type: git
    enabled: true
    repo_path: .
    allowed_actions:
      - git_revert
      - git_cherry_pick
      - git_apply_patch
    dry_run: false

  # ---------------------------------------------------------------------------
  # SHELL EXECUTOR - Run shell commands
  # ---------------------------------------------------------------------------
  - type: shell
    enabled: true
    # SECURITY: Only whitelisted commands can be executed
    allowed_commands:
      - systemctl restart myapp
      - docker-compose restart
      - npm run build
      - npm install
      - pip install                    # Allow AI to install missing packages
      - pm2 restart all
    dry_run: false

  # ---------------------------------------------------------------------------
  # KUBERNETES EXECUTOR - K8s operations
  # ---------------------------------------------------------------------------
  - type: kubernetes
    enabled: false
    allowed_actions:
      - restart      # Restart pods
      - rollback     # Rollback to previous deployment
      - scale_up     # Scale up replicas

# =============================================================================
# GUARDRAILS - Safety Settings
# =============================================================================
# IMPORTANT: Configure these carefully for your risk tolerance.
guardrails:

  # AI Confidence Threshold (0.0 - 1.0)
  # Only take action if AI confidence is above this level
  confidence_threshold: 0.7

  # Require User Confirmation
  # true = Always ask before executing fixes (recommended for production)
  # false = Allow AI to suggest fixes without asking
  require_confirmation: false

  # Auto-Fix Mode
  # true = Automatically apply fixes if confidence is high enough
  # false = Never auto-apply, always require confirmation or just suggest
  # WARNING: Cannot be true if require_confirmation is also true
  auto_fix_enabled: true

  # Rate Limiting
  # Maximum number of remediation actions per hour
  max_actions_per_hour: 10

  # Allowed Action Types
  # Only these action types can be executed
  allowed_action_types:
    - restart
    - rollback
    - scale_up
    - alert_only
    - git_revert
    - file_edit        # Allow AI to edit/fix code
    - cmd_exec         # Allow AI to run shell commands

  # SECURITY: Paths that should NEVER be modified
  blocked_paths:
    - /etc/*
    - /usr/*
    - /bin/*
    - /sbin/*
    - ~/.ssh/*
    - ~/.aws/*

  # SECURITY: Commands that should NEVER be executed
  blocked_commands:
    - rm -rf /
    - rm -rf /*
    - dd if=
    - mkfs
    - "> /dev/"
    - chmod 777

# =============================================================================
# NOTIFICATIONS - Where to Send Alerts
# =============================================================================
notifications:
  # Slack Integration
  slack_webhook: ${SLACK_WEBHOOK_URL}
  # slack_channel: "#incidents"

  # Email Integration (optional)
  # email_to:
  #   - ops@example.com
  #   - oncall@example.com
  # email_from: remediate@example.com
  # smtp_host: smtp.example.com
  # smtp_port: 587

  # What events trigger notifications
  on_detection: true      # When an error is detected
  on_diagnosis: true      # When AI provides diagnosis
  on_remediation: true    # When a fix is applied
  on_failure: true        # When remediation fails

# =============================================================================
# GENERAL SETTINGS
# =============================================================================

# How often to scan for errors (seconds)
poll_interval: 10.0

# Ignore duplicate errors within this window (seconds)
dedup_window_seconds: 60

# Logging level: DEBUG, INFO, WARNING, ERROR
log_level: INFO

# Directory for storing incident history
data_dir: ./data/incidents

