"""add_password_reset_fields

Revision ID: 05d85a041435
Revises: 723f7fb68319
Create Date: 2025-12-27 03:03:40.183091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d85a041435'
down_revision: Union[str, Sequence[str], None] = '723f7fb68319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding (for SQLite/PostgreSQL compatibility)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_columns = [col['name'] for col in inspector.get_columns('users')]

    if 'reset_token' not in existing_columns:
        op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))

    if 'reset_token_expires' not in existing_columns:
        op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))

    # Create index if it doesn't exist
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('users')]
    if 'ix_users_reset_token' not in existing_indexes:
        op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    except:
        pass
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
