"""add_email_verification_fields

Revision ID: 723f7fb68319
Revises: ac9f76f179f0
Create Date: 2025-12-27 02:57:15.589863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '723f7fb68319'
down_revision: Union[str, Sequence[str], None] = 'ac9f76f179f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding (for SQLite/PostgreSQL compatibility)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_columns = [col['name'] for col in inspector.get_columns('users')]

    if 'email_verified' not in existing_columns:
        # PostgreSQL-compatible: use False instead of 0 for boolean
        op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True, server_default='false'))
        op.execute("UPDATE users SET email_verified = False WHERE email_verified IS NULL")

    if 'verification_token' not in existing_columns:
        op.add_column('users', sa.Column('verification_token', sa.String(length=255), nullable=True))

    if 'verification_token_expires' not in existing_columns:
        op.add_column('users', sa.Column('verification_token_expires', sa.DateTime(timezone=True), nullable=True))

    # Create index if it doesn't exist
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('users')]
    if 'ix_users_verification_token' not in existing_indexes:
        op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)

    # Note: Removed ALTER COLUMN for hashed_password - SQLite doesn't support it
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    # Note: Removed ALTER COLUMN for hashed_password - SQLite doesn't support it
    op.drop_column('users', 'verification_token_expires')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
